// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeyR13y_3Hzf1wWwK55xJVUFopNnJfhDY',
    appId: '1:28845198054:web:b6cb39ff5bfa59fcf6c927',
    messagingSenderId: '28845198054',
    projectId: 'gam3ty-46268',
    authDomain: 'gam3ty-46268.firebaseapp.com',
    storageBucket: 'gam3ty-46268.firebasestorage.app',
    measurementId: 'G-ES0BH7QZ03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMehW4JBniH1ai4MxluqWl9nSLqOCrQRE',
    appId: '1:28845198054:android:77af64006b60d957f6c927',
    messagingSenderId: '28845198054',
    projectId: 'gam3ty-46268',
    storageBucket: 'gam3ty-46268.firebasestorage.app',
  );
}
